-- Migration to create leads table for AI lead scoring and matching

CREATE TABLE IF NOT EXISTS leads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    raw_inquiry TEXT,
    ai_score INTEGER DEFAULT 0,
    ai_assessment JSONB DEFAULT '{}'::jsonb,
    matched_property_ids UUID[] DEFAULT '{}'::uuid[],
    status TEXT DEFAULT 'new', -- new, contacted, qualified, lost
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for lead lookups and status filtering
CREATE INDEX idx_leads_tenant_status ON leads(tenant_id, status);
CREATE INDEX idx_leads_email ON leads(email);

-- Table for storing AI-generated property matches for leads
CREATE TABLE IF NOT EXISTS lead_property_matches (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
    property_id UUID REFERENCES properties(id) ON DELETE CASCADE,
    tenant_id UUID NOT NULL,
    match_score INTEGER NOT NULL,
    match_reasons JSONB DEFAULT '[]'::jsonb,
    mismatch_reasons JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(lead_id, property_id)
);

CREATE INDEX idx_matches_lead_score ON lead_property_matches(lead_id, match_score DESC);

-- Table for CRM Tasks generated by AI
CREATE TABLE IF NOT EXISTS crm_tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    action_type TEXT NOT NULL, -- call, email, showing, followup
    priority TEXT NOT NULL, -- HIGH, MEDIUM, LOW
    due_date TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'OPEN', -- OPEN, COMPLETED, CANCELLED
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_tasks_tenant_status ON crm_tasks(tenant_id, status);
CREATE INDEX idx_tasks_lead ON crm_tasks(lead_id);
